# Generated by Django 3.2 on 2021-05-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=80)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_age', models.IntegerField()),
            ],
        ),
    ]
